language: node_js
node_js:
  - "12"
branches:
  only: 
    - main
notifications:
  # in real case you probably want to remove it or set to true
  email: false
script:
  - npm install -g @abaplint/cli
  - abaplint
